"""Localized showcase copy; no company biography or studio claims."""
KEYS='title|intro|collectionBody|contactBody|all|tools|learn|games|reading|speaking|notes|study|tasks|diction|arcade|voicegame|habits'.split('|')
ROWS={
'en':'Find your<br>next favourite.|Explore apps for reading, notes, learning and everyday planning, plus games for a quick break.|Open an app page for features, screenshots and download links.|Need help? Email your question and the name of the app.|All|Everyday tools|Learning|Games|Books and reading habits|Daily speaking practice|Notes and folders|Lessons and attendance|Tasks and daily planning|Diction and reading aloud|One-tap jumping game|Pop balloons with your voice|Habits and daily streaks',
'tr':'Yeni favorini<br>keşfet.|Okumak, not almak, öğrenmek ve günlük planlarını düzenlemek için uygulamalar; kısa molalar için oyunlar.|Özellikleri, ekran görüntülerini ve indirme bağlantılarını görmek için bir uygulamayı incele.|Yardıma mı ihtiyacın var? Sorunu ve uygulamanın adını e-postayla ilet.|Tümü|Günlük araçlar|Öğrenme|Oyunlar|Kitaplar ve okuma alışkanlığı|Günlük konuşma pratiği|Notlar ve klasörler|Dersler ve devamsızlık|Görevler ve günlük planlar|Diksiyon ve sesli okuma|Tek dokunuşla zıplama oyunu|Sesinle balonları patlat|Alışkanlıklar ve günlük seriler',
'ar':'اكتشف تطبيقك<br>المفضل التالي.|تطبيقات للقراءة والملاحظات والتعلم والتخطيط اليومي، وألعاب لاستراحة قصيرة.|افتح صفحة التطبيق للاطلاع على الميزات ولقطات الشاشة وروابط التنزيل.|تحتاج إلى مساعدة؟ أرسل سؤالك واسم التطبيق بالبريد الإلكتروني.|الكل|أدوات يومية|التعلم|الألعاب|الكتب وعادات القراءة|تدريب يومي على التحدث|الملاحظات والمجلدات|الدروس والغياب|المهام والتخطيط اليومي|النطق والقراءة بصوت عالٍ|لعبة قفز بلمسة واحدة|فرقع البالونات بصوتك|العادات والسلاسل اليومية',
'da':'Find din<br>næste favorit.|Udforsk apps til læsning, noter, læring og daglig planlægning samt spil til en kort pause.|Åbn en appside for funktioner, skærmbilleder og downloadlinks.|Brug for hjælp? Send dit spørgsmål og appens navn via e-mail.|Alle|Hverdagsværktøjer|Læring|Spil|Bøger og læsevaner|Daglig taletræning|Noter og mapper|Undervisning og fravær|Opgaver og daglige planer|Diktion og højtlæsning|Hoppespil med ét tryk|Spræng balloner med stemmen|Vaner og daglige streaks',
'de':'Entdecke deinen<br>nächsten Favoriten.|Apps zum Lesen, Notieren, Lernen und Planen sowie Spiele für eine kurze Pause.|Auf der Appseite findest du Funktionen, Screenshots und Downloadlinks.|Brauchst du Hilfe? Sende deine Frage und den Namen der App per E-Mail.|Alle|Alltagshelfer|Lernen|Spiele|Bücher und Lesegewohnheiten|Tägliche Sprechübungen|Notizen und Ordner|Unterricht und Fehlzeiten|Aufgaben und Tagesplanung|Diktion und Vorlesen|Sprungspiel mit einem Tippen|Lass Ballons mit deiner Stimme platzen|Gewohnheiten und tägliche Serien',
'el':'Βρες την επόμενη<br>αγαπημένη σου εφαρμογή.|Εφαρμογές για ανάγνωση, σημειώσεις, μάθηση και καθημερινό προγραμματισμό, μαζί με παιχνίδια για ένα μικρό διάλειμμα.|Άνοιξε τη σελίδα μιας εφαρμογής για λειτουργίες, στιγμιότυπα και συνδέσμους λήψης.|Χρειάζεσαι βοήθεια; Στείλε την ερώτησή σου και το όνομα της εφαρμογής με email.|Όλες|Καθημερινά εργαλεία|Μάθηση|Παιχνίδια|Βιβλία και συνήθειες ανάγνωσης|Καθημερινή εξάσκηση ομιλίας|Σημειώσεις και φάκελοι|Μαθήματα και απουσίες|Εργασίες και καθημερινά σχέδια|Άρθρωση και ανάγνωση δυνατά|Παιχνίδι άλματος με ένα άγγιγμα|Σκάσε μπαλόνια με τη φωνή σου|Συνήθειες και καθημερινά σερί',
'es':'Encuentra tu<br>próxima favorita.|Explora apps para leer, tomar notas, aprender y organizar tu día, además de juegos para un breve descanso.|Abre la página de una app para ver funciones, capturas y enlaces de descarga.|¿Necesitas ayuda? Envía tu pregunta y el nombre de la app por correo.|Todas|Herramientas diarias|Aprendizaje|Juegos|Libros y hábitos de lectura|Práctica diaria de conversación|Notas y carpetas|Clases y asistencia|Tareas y planificación diaria|Dicción y lectura en voz alta|Juego de saltos con un toque|Explota globos con tu voz|Hábitos y rachas diarias',
'fi':'Löydä seuraava<br>suosikkisi.|Tutustu lukemisen, muistiinpanojen, oppimisen ja arjen suunnittelun sovelluksiin sekä peleihin pientä taukoa varten.|Avaa sovelluksen sivu nähdäksesi ominaisuudet, kuvakaappaukset ja latauslinkit.|Tarvitsetko apua? Lähetä kysymyksesi ja sovelluksen nimi sähköpostitse.|Kaikki|Arjen työkalut|Oppiminen|Pelit|Kirjat ja lukutottumukset|Päivittäinen puheharjoittelu|Muistiinpanot ja kansiot|Oppitunnit ja poissaolot|Tehtävät ja päiväsuunnitelmat|Diktio ja ääneen lukeminen|Hyppypeli yhdellä napautuksella|Puhkaise ilmapalloja äänelläsi|Tottumukset ja päivittäiset putket',
'fil':'Hanapin ang susunod<br>mong paborito.|Tuklasin ang mga app para sa pagbabasa, mga tala, pag-aaral at pang-araw-araw na plano, pati mga laro para sa maikling pahinga.|Buksan ang pahina ng app para sa mga tampok, screenshot at link sa pag-download.|Kailangan ng tulong? I-email ang iyong tanong at ang pangalan ng app.|Lahat|Mga gamit sa araw-araw|Pag-aaral|Mga laro|Mga libro at gawi sa pagbabasa|Araw-araw na pagsasanay sa pagsasalita|Mga tala at folder|Mga klase at pagliban|Mga gawain at pang-araw-araw na plano|Diksiyon at pagbasa nang malakas|Larong pagtalon sa isang tap|Paputukin ang mga lobo gamit ang boses|Mga gawi at araw-araw na streak',
'fr':'Trouvez votre<br>prochaine favorite.|Découvrez des applications pour lire, prendre des notes, apprendre et organiser votre journée, ainsi que des jeux pour une courte pause.|Ouvrez la page d’une application pour ses fonctionnalités, captures et liens de téléchargement.|Besoin d’aide ? Envoyez votre question et le nom de l’application par e-mail.|Toutes|Outils du quotidien|Apprentissage|Jeux|Livres et habitudes de lecture|Pratique orale quotidienne|Notes et dossiers|Cours et absences|Tâches et organisation quotidienne|Diction et lecture à voix haute|Jeu de saut à une touche|Éclatez des ballons avec votre voix|Habitudes et séries quotidiennes',
'hi':'अपना अगला<br>पसंदीदा ऐप खोजें।|पढ़ने, नोट्स लिखने, सीखने और दिन की योजना बनाने वाले ऐप देखें, साथ में छोटे विराम के लिए खेल भी।|सुविधाएँ, स्क्रीनशॉट और डाउनलोड लिंक देखने के लिए ऐप का पेज खोलें।|मदद चाहिए? अपना सवाल और ऐप का नाम ईमेल करें।|सभी|रोज़मर्रा के साधन|सीखना|खेल|किताबें और पढ़ने की आदतें|रोज़ बोलने का अभ्यास|नोट्स और फ़ोल्डर|कक्षाएँ और अनुपस्थिति|काम और दैनिक योजना|उच्चारण और ज़ोर से पढ़ना|एक टैप वाला कूदने का खेल|अपनी आवाज़ से गुब्बारे फोड़ें|आदतें और रोज़ की स्ट्रीक',
'id':'Temukan favorit<br>Anda berikutnya.|Jelajahi aplikasi untuk membaca, mencatat, belajar dan merencanakan hari, serta gim untuk istirahat singkat.|Buka halaman aplikasi untuk fitur, tangkapan layar dan tautan unduhan.|Butuh bantuan? Kirim pertanyaan dan nama aplikasi melalui email.|Semua|Alat sehari-hari|Belajar|Gim|Buku dan kebiasaan membaca|Latihan berbicara harian|Catatan dan folder|Pelajaran dan kehadiran|Tugas dan rencana harian|Diksi dan membaca nyaring|Gim lompat satu ketukan|Pecahkan balon dengan suara Anda|Kebiasaan dan streak harian',
'it':'Trova la tua<br>prossima preferita.|Scopri app per leggere, prendere appunti, imparare e organizzare la giornata, insieme a giochi per una breve pausa.|Apri la pagina di un’app per funzionalità, schermate e link per scaricarla.|Serve aiuto? Invia la tua domanda e il nome dell’app via e-mail.|Tutte|Strumenti quotidiani|Apprendimento|Giochi|Libri e abitudini di lettura|Pratica orale quotidiana|Note e cartelle|Lezioni e assenze|Attività e piani giornalieri|Dizione e lettura ad alta voce|Gioco di salti con un tocco|Scoppia i palloncini con la voce|Abitudini e serie quotidiane',
'ja':'次のお気に入りを<br>見つけよう。|読書、メモ、学習、日々の予定管理に役立つアプリと、ちょっとした休憩に楽しめるゲームを探してみましょう。|アプリのページで機能、スクリーンショット、ダウンロードリンクを確認できます。|お困りですか？ご質問とアプリ名をメールでお送りください。|すべて|日常のツール|学習|ゲーム|本と読書習慣の記録|毎日のスピーキング練習|メモとフォルダ|授業と出欠の管理|タスクと毎日の予定|発音と音読の練習|ワンタップのジャンプゲーム|声で風船を割るゲーム|習慣と毎日の連続記録',
'ko':'다음에 좋아할 앱을<br>찾아보세요.|독서, 메모, 학습, 일상 계획을 위한 앱과 짧은 휴식에 즐길 게임을 만나보세요.|앱 페이지에서 기능, 스크린샷, 다운로드 링크를 확인하세요.|도움이 필요한가요? 질문과 앱 이름을 이메일로 보내 주세요.|전체|일상 도구|학습|게임|책과 독서 습관|매일 말하기 연습|메모와 폴더|수업과 출결 관리|할 일과 일상 계획|발음과 소리 내어 읽기|한 번의 터치로 점프하는 게임|목소리로 풍선을 터뜨리는 게임|습관과 매일의 연속 기록',
'ms':'Temukan kegemaran<br>anda yang seterusnya.|Terokai aplikasi untuk membaca, mencatat, belajar dan merancang hari, serta permainan untuk rehat singkat.|Buka halaman aplikasi untuk ciri, tangkap layar dan pautan muat turun.|Perlukan bantuan? E-mel soalan anda bersama nama aplikasi.|Semua|Alat harian|Pembelajaran|Permainan|Buku dan tabiat membaca|Latihan pertuturan harian|Nota dan folder|Kelas dan kehadiran|Tugasan dan rancangan harian|Diksi dan bacaan kuat|Permainan melompat satu ketikan|Pecahkan belon dengan suara anda|Tabiat dan rentetan harian',
'nb':'Finn din<br>neste favoritt.|Utforsk apper for lesing, notater, læring og daglig planlegging, og spill til en kort pause.|Åpne appsiden for funksjoner, skjermbilder og nedlastingslenker.|Trenger du hjelp? Send spørsmålet ditt og navnet på appen på e-post.|Alle|Hverdagsverktøy|Læring|Spill|Bøker og lesevaner|Daglig taleøving|Notater og mapper|Undervisning og fravær|Oppgaver og dagsplaner|Diksjon og høytlesing|Hoppespill med ett trykk|Sprekk ballonger med stemmen|Vaner og daglige rekker',
'nl':'Vind je<br>volgende favoriet.|Ontdek apps om te lezen, notities te maken, te leren en je dag te plannen, plus spellen voor een korte pauze.|Open een apppagina voor functies, schermafbeeldingen en downloadlinks.|Hulp nodig? Mail je vraag en de naam van de app.|Alle|Dagelijkse hulpmiddelen|Leren|Spellen|Boeken en leesgewoonten|Dagelijkse spreekoefeningen|Notities en mappen|Lessen en aanwezigheid|Taken en dagelijkse plannen|Dictie en hardop lezen|Springspel met één tik|Laat ballonnen knappen met je stem|Gewoonten en dagelijkse reeksen',
'pl':'Znajdź kolejną<br>ulubioną aplikację.|Odkryj aplikacje do czytania, notatek, nauki i planowania dnia oraz gry na krótką przerwę.|Otwórz stronę aplikacji, aby zobaczyć funkcje, zrzuty ekranu i linki do pobrania.|Potrzebujesz pomocy? Wyślij e-mailem pytanie i nazwę aplikacji.|Wszystkie|Narzędzia na co dzień|Nauka|Gry|Książki i nawyki czytelnicze|Codzienne ćwiczenia mówienia|Notatki i foldery|Lekcje i obecność|Zadania i plany dnia|Dykcja i czytanie na głos|Gra w skakanie jednym dotknięciem|Przebijaj balony głosem|Nawyki i codzienne serie',
'pt':'Encontre a sua<br>próxima favorita.|Explore aplicações para ler, tomar notas, aprender e organizar o dia, além de jogos para uma pausa breve.|Abra a página de uma aplicação para ver funcionalidades, capturas e ligações de transferência.|Precisa de ajuda? Envie a sua pergunta e o nome da aplicação por e-mail.|Todas|Ferramentas diárias|Aprendizagem|Jogos|Livros e hábitos de leitura|Prática diária de conversação|Notas e pastas|Aulas e assiduidade|Tarefas e planos diários|Dicção e leitura em voz alta|Jogo de saltos com um toque|Rebente balões com a sua voz|Hábitos e sequências diárias',
'ro':'Găsește următoarea<br>ta aplicație preferată.|Descoperă aplicații pentru citit, notițe, învățare și planificarea zilei, plus jocuri pentru o scurtă pauză.|Deschide pagina unei aplicații pentru funcții, capturi de ecran și linkuri de descărcare.|Ai nevoie de ajutor? Trimite întrebarea și numele aplicației prin e-mail.|Toate|Instrumente zilnice|Învățare|Jocuri|Cărți și obiceiuri de lectură|Exersarea zilnică a vorbirii|Notițe și foldere|Cursuri și absențe|Sarcini și planuri zilnice|Dicție și citit cu voce tare|Joc de sărituri cu o atingere|Sparge baloane cu vocea ta|Obiceiuri și serii zilnice',
'ru':'Найдите новое<br>любимое приложение.|Приложения для чтения, заметок, обучения и планирования дня, а также игры для короткого перерыва.|Откройте страницу приложения, чтобы посмотреть функции, снимки экрана и ссылки для скачивания.|Нужна помощь? Напишите вопрос и название приложения по электронной почте.|Все|Повседневные инструменты|Обучение|Игры|Книги и привычки чтения|Ежедневная разговорная практика|Заметки и папки|Занятия и посещаемость|Задачи и планы на день|Дикция и чтение вслух|Прыжки одним касанием|Лопайте шарики голосом|Привычки и ежедневные серии',
'sv':'Hitta din<br>nästa favorit.|Utforska appar för läsning, anteckningar, lärande och vardagsplanering samt spel för en kort paus.|Öppna appsidan för funktioner, skärmbilder och nedladdningslänkar.|Behöver du hjälp? Mejla din fråga och appens namn.|Alla|Vardagsverktyg|Lärande|Spel|Böcker och läsvanor|Daglig talträning|Anteckningar och mappar|Lektioner och frånvaro|Uppgifter och dagsplaner|Diktion och högläsning|Hoppspel med ett tryck|Spräck ballonger med rösten|Vanor och dagliga sviter',
'th':'ค้นพบแอปโปรด<br>ตัวต่อไปของคุณ|สำรวจแอปสำหรับอ่านหนังสือ จดบันทึก เรียนรู้ และวางแผนประจำวัน พร้อมเกมสำหรับพักสั้น ๆ|เปิดหน้าแอปเพื่อดูคุณสมบัติ ภาพหน้าจอ และลิงก์ดาวน์โหลด|ต้องการความช่วยเหลือใช่ไหม ส่งคำถามและชื่อแอปทางอีเมล|ทั้งหมด|เครื่องมือประจำวัน|การเรียนรู้|เกม|หนังสือและนิสัยการอ่าน|ฝึกพูดทุกวัน|บันทึกและโฟลเดอร์|บทเรียนและการเข้าเรียน|งานและแผนประจำวัน|การออกเสียงและอ่านออกเสียง|เกมกระโดดด้วยการแตะครั้งเดียว|ทำให้ลูกโป่งแตกด้วยเสียงของคุณ|นิสัยและสถิติต่อเนื่องรายวัน',
'vi':'Tìm ứng dụng<br>yêu thích tiếp theo.|Khám phá ứng dụng để đọc sách, ghi chú, học tập và lên kế hoạch mỗi ngày, cùng trò chơi cho giờ nghỉ ngắn.|Mở trang ứng dụng để xem tính năng, ảnh chụp màn hình và liên kết tải xuống.|Cần hỗ trợ? Gửi câu hỏi và tên ứng dụng qua email.|Tất cả|Công cụ hằng ngày|Học tập|Trò chơi|Sách và thói quen đọc|Luyện nói hằng ngày|Ghi chú và thư mục|Lớp học và điểm danh|Công việc và kế hoạch hằng ngày|Phát âm và đọc thành tiếng|Trò chơi nhảy bằng một chạm|Làm nổ bóng bằng giọng nói|Thói quen và chuỗi ngày liên tiếp',
'zh':'发现你的<br>下一款心仪应用。|探索阅读、笔记、学习和日常规划应用，还有适合短暂休息的游戏。|打开应用页面，查看功能、截图和下载链接。|需要帮助？请通过电子邮件发送问题和应用名称。|全部|日常工具|学习|游戏|书籍与阅读习惯|每日口语练习|笔记与文件夹|课程与出勤记录|任务与每日计划|发音与朗读练习|单指点击跳跃游戏|用声音戳破气球|习惯与每日连胜',
}
HOME={lang:dict(zip(KEYS,row.split('|'),strict=True)) for lang,row in ROWS.items()}
COUNTS={'en':'9 apps','tr':'9 uygulama','ar':'9 تطبيقات','da':'9 apps','de':'9 Apps','el':'9 εφαρμογές','es':'9 apps','fi':'9 sovellusta','fil':'9 app','fr':'9 applications','hi':'9 ऐप','id':'9 aplikasi','it':'9 app','ja':'9つのアプリ','ko':'9개 앱','ms':'9 aplikasi','nb':'9 apper','nl':'9 apps','pl':'9 aplikacji','pt':'9 aplicações','ro':'9 aplicații','ru':'9 приложений','sv':'9 appar','th':'9 แอป','vi':'9 ứng dụng','zh':'9 款应用'}
for lang,copy in HOME.items(): copy['count']=COUNTS[lang]
