"""Small shared interface dictionary. Product copy lives in apps.json."""
KEYS = 'apps|about|support|language|explore|features|screens|languages|getApp|contact|privacy|terms|back|comingSoon|imageNote|englishLegal|skip|close|previous|next|moreApps'.split('|')
ROWS = {
'en': 'Apps|About|Support|Language|Explore|What you can do|A closer look|Available languages|Get the app|Contact us|Privacy policy|Terms of use|All apps|Coming soon|Store screenshots. Appearance may vary by version and language.|Legal text in English|Skip to content|Close|Previous|Next|More from Rapheldor',
'tr': 'Uygulamalar|Hakkımızda|Destek|Dil|İncele|Neler yapabilirsin?|Yakından bak|Desteklenen diller|Uygulamayı edin|Bize ulaş|Gizlilik politikası|Kullanım koşulları|Tüm uygulamalar|Yakında|Mağaza ekran görüntüleri. Görünüm sürüme ve dile göre değişebilir.|Hukuki metin İngilizcedir|İçeriğe geç|Kapat|Önceki|Sonraki|Rapheldor’dan diğer uygulamalar',
'ar': 'التطبيقات|من نحن|الدعم|اللغة|استكشف|ما الذي يمكنك فعله|نظرة أقرب|اللغات المتاحة|احصل على التطبيق|تواصل معنا|سياسة الخصوصية|شروط الاستخدام|جميع التطبيقات|قريباً|لقطات من المتجر. قد يختلف المظهر حسب الإصدار واللغة.|النص القانوني بالإنجليزية|انتقل إلى المحتوى|إغلاق|السابق|التالي|المزيد من Rapheldor',
'da': 'Apps|Om os|Support|Sprog|Udforsk|Det kan du gøre|Se nærmere|Tilgængelige sprog|Hent appen|Kontakt os|Privatlivspolitik|Brugsvilkår|Alle apps|Kommer snart|Skærmbilleder fra butikken. Udseendet kan variere efter version og sprog.|Juridisk tekst på engelsk|Spring til indhold|Luk|Forrige|Næste|Mere fra Rapheldor',
'de': 'Apps|Über uns|Support|Sprache|Entdecken|Das kannst du tun|Ein genauerer Blick|Verfügbare Sprachen|App herunterladen|Kontakt|Datenschutzerklärung|Nutzungsbedingungen|Alle Apps|Demnächst|Store-Screenshots. Die Darstellung kann je nach Version und Sprache variieren.|Rechtlicher Text auf Englisch|Zum Inhalt springen|Schließen|Zurück|Weiter|Mehr von Rapheldor',
'el': 'Εφαρμογές|Σχετικά με εμάς|Υποστήριξη|Γλώσσα|Εξερεύνηση|Τι μπορείς να κάνεις|Μια πιο κοντινή ματιά|Διαθέσιμες γλώσσες|Λήψη εφαρμογής|Επικοινωνία|Πολιτική απορρήτου|Όροι χρήσης|Όλες οι εφαρμογές|Σύντομα|Στιγμιότυπα από το κατάστημα. Η εμφάνιση μπορεί να διαφέρει ανά έκδοση και γλώσσα.|Νομικό κείμενο στα αγγλικά|Μετάβαση στο περιεχόμενο|Κλείσιμο|Προηγούμενο|Επόμενο|Περισσότερα από τη Rapheldor',
'es': 'Aplicaciones|Sobre nosotros|Ayuda|Idioma|Explorar|Qué puedes hacer|Más de cerca|Idiomas disponibles|Descargar la app|Contacto|Política de privacidad|Condiciones de uso|Todas las apps|Próximamente|Capturas de la tienda. El aspecto puede variar según la versión y el idioma.|Texto legal en inglés|Ir al contenido|Cerrar|Anterior|Siguiente|Más de Rapheldor',
'fi': 'Sovellukset|Tietoa meistä|Tuki|Kieli|Tutustu|Mitä voit tehdä|Katso tarkemmin|Saatavilla olevat kielet|Lataa sovellus|Ota yhteyttä|Tietosuojakäytäntö|Käyttöehdot|Kaikki sovellukset|Tulossa pian|Kaupan kuvakaappaukset. Ulkoasu voi vaihdella version ja kielen mukaan.|Lakiteksti englanniksi|Siirry sisältöön|Sulje|Edellinen|Seuraava|Lisää Rapheldorilta',
'fil': 'Mga app|Tungkol sa amin|Suporta|Wika|Tuklasin|Ano ang magagawa mo|Mas malapit na tingin|Mga available na wika|Kunin ang app|Makipag-ugnayan|Patakaran sa privacy|Mga tuntunin sa paggamit|Lahat ng app|Malapit na|Mga screenshot mula sa store. Maaaring mag-iba ang hitsura ayon sa bersyon at wika.|Legal na teksto sa Ingles|Pumunta sa nilalaman|Isara|Nakaraan|Susunod|Higit pa mula sa Rapheldor',
'fr': 'Applications|À propos|Assistance|Langue|Découvrir|Ce que vous pouvez faire|De plus près|Langues disponibles|Télécharger l’application|Nous contacter|Politique de confidentialité|Conditions d’utilisation|Toutes les applications|Bientôt disponible|Captures du store. L’apparence peut varier selon la version et la langue.|Texte juridique en anglais|Aller au contenu|Fermer|Précédent|Suivant|D’autres apps Rapheldor',
'hi': 'ऐप|हमारे बारे में|सहायता|भाषा|देखें|आप क्या कर सकते हैं|करीब से देखें|उपलब्ध भाषाएँ|ऐप डाउनलोड करें|संपर्क करें|गोपनीयता नीति|उपयोग की शर्तें|सभी ऐप|जल्द आ रहा है|स्टोर के स्क्रीनशॉट। रूप संस्करण और भाषा के अनुसार बदल सकता है।|कानूनी पाठ अंग्रेज़ी में है|सामग्री पर जाएँ|बंद करें|पिछला|अगला|Rapheldor के और ऐप',
'id': 'Aplikasi|Tentang kami|Dukungan|Bahasa|Jelajahi|Yang bisa Anda lakukan|Lihat lebih dekat|Bahasa tersedia|Unduh aplikasi|Hubungi kami|Kebijakan privasi|Ketentuan penggunaan|Semua aplikasi|Segera hadir|Tangkapan layar toko. Tampilan dapat berbeda menurut versi dan bahasa.|Teks hukum dalam bahasa Inggris|Lewati ke konten|Tutup|Sebelumnya|Berikutnya|Lainnya dari Rapheldor',
'it': 'App|Chi siamo|Assistenza|Lingua|Scopri|Cosa puoi fare|Uno sguardo più vicino|Lingue disponibili|Scarica l’app|Contattaci|Informativa sulla privacy|Condizioni d’uso|Tutte le app|In arrivo|Schermate dello store. L’aspetto può variare in base alla versione e alla lingua.|Testo legale in inglese|Vai al contenuto|Chiudi|Precedente|Successivo|Altre app Rapheldor',
'ja': 'アプリ|私たちについて|サポート|言語|詳しく見る|できること|画面を見てみよう|対応言語|アプリを入手|お問い合わせ|プライバシーポリシー|利用規約|すべてのアプリ|近日公開|ストアのスクリーンショットです。表示はバージョンや言語により異なる場合があります。|法的文書は英語です|本文へ移動|閉じる|前へ|次へ|Rapheldorのほかのアプリ',
'ko': '앱|소개|지원|언어|둘러보기|할 수 있는 일|자세히 보기|지원 언어|앱 다운로드|문의하기|개인정보 처리방침|이용약관|모든 앱|출시 예정|스토어 스크린샷입니다. 버전과 언어에 따라 화면이 다를 수 있습니다.|법률 문서는 영어로 제공됩니다|본문으로 이동|닫기|이전|다음|Rapheldor의 다른 앱',
'ms': 'Aplikasi|Tentang kami|Sokongan|Bahasa|Terokai|Apa yang boleh anda lakukan|Lihat lebih dekat|Bahasa tersedia|Dapatkan aplikasi|Hubungi kami|Dasar privasi|Terma penggunaan|Semua aplikasi|Akan datang|Tangkapan skrin kedai. Paparan mungkin berbeza mengikut versi dan bahasa.|Teks undang-undang dalam bahasa Inggeris|Langkau ke kandungan|Tutup|Sebelumnya|Seterusnya|Lagi daripada Rapheldor',
'nb': 'Apper|Om oss|Brukerstøtte|Språk|Utforsk|Dette kan du gjøre|Se nærmere|Tilgjengelige språk|Last ned appen|Kontakt oss|Personvernerklæring|Bruksvilkår|Alle apper|Kommer snart|Skjermbilder fra butikken. Utseendet kan variere med versjon og språk.|Juridisk tekst på engelsk|Hopp til innhold|Lukk|Forrige|Neste|Mer fra Rapheldor',
'nl': 'Apps|Over ons|Ondersteuning|Taal|Ontdek|Wat je kunt doen|Van dichtbij|Beschikbare talen|Download de app|Neem contact op|Privacybeleid|Gebruiksvoorwaarden|Alle apps|Binnenkort|Schermafbeeldingen uit de winkel. De weergave kan per versie en taal verschillen.|Juridische tekst in het Engels|Ga naar inhoud|Sluiten|Vorige|Volgende|Meer van Rapheldor',
'pl': 'Aplikacje|O nas|Pomoc|Język|Odkryj|Co możesz zrobić|Przyjrzyj się bliżej|Dostępne języki|Pobierz aplikację|Kontakt|Polityka prywatności|Warunki użytkowania|Wszystkie aplikacje|Już wkrótce|Zrzuty ekranu ze sklepu. Wygląd może się różnić zależnie od wersji i języka.|Tekst prawny po angielsku|Przejdź do treści|Zamknij|Poprzedni|Następny|Więcej od Rapheldor',
'pt': 'Aplicações|Sobre nós|Suporte|Idioma|Explorar|O que pode fazer|Veja de perto|Idiomas disponíveis|Obter a aplicação|Contacte-nos|Política de privacidade|Termos de utilização|Todas as aplicações|Em breve|Capturas da loja. O aspeto pode variar conforme a versão e o idioma.|Texto jurídico em inglês|Ir para o conteúdo|Fechar|Anterior|Seguinte|Mais da Rapheldor',
'ro': 'Aplicații|Despre noi|Asistență|Limbă|Descoperă|Ce poți face|Privește mai atent|Limbi disponibile|Descarcă aplicația|Contactează-ne|Politica de confidențialitate|Condiții de utilizare|Toate aplicațiile|În curând|Capturi din magazin. Aspectul poate varia în funcție de versiune și limbă.|Text juridic în engleză|Sari la conținut|Închide|Anterior|Următorul|Mai multe de la Rapheldor',
'ru': 'Приложения|О нас|Поддержка|Язык|Подробнее|Что можно делать|Рассмотрите поближе|Доступные языки|Скачать приложение|Связаться с нами|Политика конфиденциальности|Условия использования|Все приложения|Скоро|Скриншоты магазина. Вид может отличаться в зависимости от версии и языка.|Юридический текст на английском|Перейти к содержимому|Закрыть|Назад|Далее|Другие приложения Rapheldor',
'sv': 'Appar|Om oss|Support|Språk|Utforska|Det här kan du göra|Titta närmare|Tillgängliga språk|Hämta appen|Kontakta oss|Integritetspolicy|Användarvillkor|Alla appar|Kommer snart|Skärmbilder från butiken. Utseendet kan variera med version och språk.|Juridisk text på engelska|Hoppa till innehållet|Stäng|Föregående|Nästa|Mer från Rapheldor',
'th': 'แอป|เกี่ยวกับเรา|การช่วยเหลือ|ภาษา|ดูรายละเอียด|สิ่งที่คุณทำได้|ดูใกล้ ๆ|ภาษาที่รองรับ|ดาวน์โหลดแอป|ติดต่อเรา|นโยบายความเป็นส่วนตัว|ข้อกำหนดการใช้งาน|แอปทั้งหมด|เร็ว ๆ นี้|ภาพหน้าจอจากสโตร์ รูปลักษณ์อาจต่างกันตามเวอร์ชันและภาษา|ข้อความทางกฎหมายเป็นภาษาอังกฤษ|ข้ามไปที่เนื้อหา|ปิด|ก่อนหน้า|ถัดไป|แอปอื่นจาก Rapheldor',
'vi': 'Ứng dụng|Giới thiệu|Hỗ trợ|Ngôn ngữ|Khám phá|Bạn có thể làm gì|Xem kỹ hơn|Ngôn ngữ hỗ trợ|Tải ứng dụng|Liên hệ|Chính sách quyền riêng tư|Điều khoản sử dụng|Tất cả ứng dụng|Sắp ra mắt|Ảnh chụp từ cửa hàng. Giao diện có thể khác theo phiên bản và ngôn ngữ.|Văn bản pháp lý bằng tiếng Anh|Đến nội dung|Đóng|Trước|Tiếp|Ứng dụng khác của Rapheldor',
'zh': '应用|关于我们|支持|语言|了解更多|你可以做什么|近距离看看|支持的语言|获取应用|联系我们|隐私政策|使用条款|所有应用|即将推出|商店截图。界面可能因版本和语言而有所不同。|法律文本为英文|跳转到正文|关闭|上一张|下一张|更多 Rapheldor 应用',
}
UI = {lang: dict(zip(KEYS, row.split('|'), strict=True)) for lang,row in ROWS.items()}
NAMES = {'en':'English','tr':'Türkçe','ar':'العربية','da':'Dansk','de':'Deutsch','el':'Ελληνικά','es':'Español','fi':'Suomi','fil':'Filipino','fr':'Français','hi':'हिन्दी','id':'Bahasa Indonesia','it':'Italiano','ja':'日本語','ko':'한국어','ms':'Bahasa Melayu','nb':'Norsk bokmål','nl':'Nederlands','pl':'Polski','pt':'Português','ro':'Română','ru':'Русский','sv':'Svenska','th':'ไทย','vi':'Tiếng Việt','zh':'简体中文'}
